#!/bin/bash

set -e

if [[ -f ./patch_flag ]];then
    echo "patched!"
    exit 0
fi

tar -zxvf kata-containers-2.1.0.tar.gz
cp -rf ./kata-containers-2.1.0/* ./
cat ./series.conf | while read line
do
    if [[ $line == '' || $line =~ ^\s*# ]]; then
        continue
    fi
    echo "====patch $line======"
    patch -p1 -F1 -s < ./patches/$line
done

touch ./patch_flag
